/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7090053e-0f2b-49cd-b079-75d25195fe2b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2CwLPU72o",
    "aws_user_pools_web_client_id": "30eu3fven9p042cvng8ajtih6s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3zuvupzfcnbhdmg5zuyv2cqb5m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7gffslmxozfwli44nxgv4mv67q",
    "aws_user_files_s3_bucket": "gratification-proof114704-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
